services:
  postgres: # Nome do serviço — pode ser qualquer nome
    image: postgres:17-alpine # Imagem base do Docker Hub
    container_name: getsecret-db # Nome fixo do container (senão Docker gera aleatório)

    environment: # Variáveis de ambiente passadas para DENTRO do container
      POSTGRES_USER: postgres # Usuário do banco
      POSTGRES_PASSWORD: postgres # Senha do banco
      POSTGRES_DB: getsecret # Nome do banco que será criado automaticamente

    ports:
      - '5432:5432' # HOST:CONTAINER — mapeia a porta do container para sua máquina

    volumes:
      - pgdata:/var/lib/postgresql/data # Persiste dados no volume nomeado

    restart: unless-stopped # Reinicia automaticamente (exceto se você parar manualmente)

    healthcheck: # Verifica se o banco está pronto
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s # Verifica a cada 10 segundos
      timeout: 5s # Timeout de cada verificação
      retries: 5 # Tenta 5 vezes antes de marcar como "unhealthy"
volumes: # Declara volumes nomeados
  pgdata:
